name: skrips
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cdo
  - python-cdo
  - pip
  - pip:
      - "f90nml"
      - "docstring_parser"
      - "typer"
      - "pyyaml"
      - git+https://github.com/prajeeshag/SphericalPolygon@sphericalpolygon@patch-1
